# Luminescence Makefile

# Configuration

PYTHON="/path/to/python"
EASYINSTALL="/path/to/easy_install"
NOSETESTS="/path/to/nosetests"
PYTHONPATH="src/"

# Targets

console:
	export PYTHONPATH=${PYTHONPATH} && ${PYTHON}

test:
	${NOSETESTS} -i should -i spec --verbose --nocapture

dist: clean
	cd src && ./setup.py sdist
	cp src/dist/* .
	rm -rf src/dist
	rm -rf src/luminescence.egg-info

tutorial:
	export PYTHONPATH=${PYTHONPATH} && ${PYTHON} src/luminescence/__init__.py docs/tutorial.yaml docs/tutorial.html

testrun:
	export PYTHONPATH=${PYTHONPATH} && ${PYTHON} src/luminescence/__init__.py test/fixtures/presentation.yaml test.html

deps:
	${EASYINSTALL} markdown2
	${EASYINSTALL} pyyaml
	${EASYINSTALL} nose
	${EASYINSTALL} mockito

clean:
	rm -f test.html
	rm -f docs/tutorial.html
	rm -f luminescence*.tar.gz
	find . -name *.pyc -exec rm {} \;

.PHONY: console test dist tutorial testrun clean